# Nav
social:
  Github: https://github.com/iocn-io
  Twitter: https://twitter.com/iocn_io

# Background image, color
background: 'url(https://iocn.io/img/button-bg.png) #f3f3f3'

# Favicon
favicon: https://iocn.io/favicon.ico

# SEO
keywords: 'iocn, i/o, io china, blockchain'

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled
